### ISSUE TITLE
When undoing/deleting an order the history is displayed twice

### ISSUE THREAD

**Issue by neumantm** [spethso/Drinklist#36] opened 2018-02-09 10:27 UTC

**Comment by mee4895** [comment] 2018-02-20 15:05
The History is renewed without being cleared first

**Comment by mee4895** [comment] 2018-05-25 16:01
Should be fixed now by all new changes implemented lately. At least I am not able to reproduce this bug anymore. If it persists on your end please reopen the issue and provide further details.

**Closed by mee4895** 2018-05-25 16:01 UTC
Labels: UserPage, bug, good first issue
